name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
    - name: Cache Gradle User Files
      uses: actions/cache@v1
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-user-home
    - name: Cache Gradle Files
      uses: actions/cache@v1
      with:
        path: ./.gradle
        key: ${{ runner.os }}-gradle-file
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      env:
        ARCLIGHT_FILES_TOKEN: ${{ secrets.ARCLIGHT_FILES_TOKEN }}
      run: |
        ./gradlew cleanBuild remapSpigotJar idea --no-daemon -i --stacktrace --refresh-dependencies --continue
        ./gradlew build collect --no-daemon -i --stacktrace --continue
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: FVS
        path: ./build/libs/*.jar
